# Use a lightweight web server to serve the static files
FROM nginx:alpine

# Copy the static files into the container
COPY index.html /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
