# Use the official Python image as a base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
# Adding only required files to the dockerfile
COPY requirements.txt .
COPY myapp.py /app/

# Install the required dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000
EXPOSE 5000

# Define the command to run the Flask application when the container starts
CMD ["python", "myapp.py"]
