apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80  # The port that the service exposes
      targetPort: 5000  # The port on the backend Pods
  type: LoadBalancer # Default type, no need to change
